# Generated by Django 5.0.6 on 2024-06-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_order',
            field=models.CharField(blank=True, help_text='Bon de commande', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='royalty',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty', to='royalties.payment', unique=True),
        ),
        migrations.AlterField(
            model_name='royalty',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalties', to='royalties.supplier'),
        ),
    ]
