# Generated by Django 5.0.6 on 2024-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0003_alter_royalty_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffusion',
            name='title',
            field=models.CharField(blank=True, help_text='Nom / lieu hor fournisseur', max_length=255),
        ),
    ]
