# Generated by Django 5.0.6 on 2024-06-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0004_diffusion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffusion',
            name='title',
            field=models.CharField(blank=True, help_text='Nom / lieu de la diffusion', max_length=255),
        ),
        migrations.AlterField(
            model_name='royalty',
            name='diffusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='royalties.diffusion'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='siret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tva_intra',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
