# Generated by Django 5.0.6 on 2024-06-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0005_alter_diffusion_title_alter_royalty_diffusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royalty',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='royalty', to='royalties.payment'),
        ),
        migrations.AlterField(
            model_name='royalty',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='royalties', to='royalties.supplier'),
        ),
    ]
