# Generated by Django 5.0.6 on 2024-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0006_alter_royalty_payment_alter_royalty_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(blank=True, help_text='Numéro', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date de paiement', null=True),
        ),
    ]
