# Generated by Django 5.0.6 on 2024-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0007_alter_payment_number_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Professeur ?'),
        ),
    ]
