# Generated by Django 5.0.6 on 2024-06-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0008_artist_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royalty',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='royalties.payment'),
        ),
    ]
